---
- name: Proxmox initial setup
  hosts: all
  gather_facts: no
  vars:
    pretask_taskandtaskcondition_message_sno: 1

  tasks:
    # `Gathering facts manually`
    - name: Gather facts manually
      setup:
