############################################################################################################
#
#
#                                  PRE_TASK, TASK_CONDITION & TASK
#
#     01. Pre gathering facts-Get and Set common variables (PRE_TASK)
#     02. Virtualization and VT-d enabled (PRE_TASK)
#     03. Prerequisites (TASK_CONDITION only)
#     04. Post install script
#     05. Post Completion Tasks and Cleanup (TASK only)
#
#
############################################################################################################
---
- name: Proxmox initial setup
  hosts: all
  gather_facts: no
  vars:
    pretask_taskandtaskcondition_message_sno: 1
    is_condition_post_install_script: false
    is_condition_post_completion_tasks_and_cleanup: false

  vars_files:
    - vault.yml

  pre_tasks:
    # `Pre gathering facts-Get and Set common variables`
    - name: ""
      import_tasks: pre_tasks/pre_gathering_facts-get_and_set_common_variables.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Virtualization and VT-d enabled` (will run only once, until forced)
    - name: ""
      import_tasks: pre_tasks/virtualization_vtd_enabled.yml
      when: not is_public_server_from_3rd_party

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

  tasks:
    # `Gathering facts manually`
    - name: Gather facts manually
      setup:

    # `Prerequisites`
    - name: ""
      import_tasks: tasks_conditions/prerequisites.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post install script` (will run only once, until forced)
    - name: ""
      import_tasks: tasks_conditions/post_install_script.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post install script`, Caller block"
      include_tasks: tasks/post_install_script.yml
      when: is_condition_post_install_script

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post Completion Tasks and Cleanup`
    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post Completion Tasks and Cleanup`, Caller block"
      include_tasks: tasks/post_completion_tasks_and_cleanup.yml
      when: is_condition_post_completion_tasks_and_cleanup
