############################################################################################################
#
#
#                                  PRE_TASK, TASK_CONDITION & TASK
#
#     01. Pre gathering facts-Get and Set common variables (PRE_TASK)
#     02. Private keys make read only (PRE_TASK)
#     03. Virtualization and VT-d enabled (PRE_TASK)
#     04. Prerequisites (TASK_CONDITION only)
#     05. Post install script
#     06. Update and upgrade
#     07. Install common packages
#     08. SSH Port
#     09. SSH Login with Key
#     10. Post Completion Tasks and Cleanup (TASK only)
#
#
############################################################################################################
---
- name: Proxmox initial setup
  hosts: all
  gather_facts: no
  vars:
    pretask_taskandtaskcondition_message_sno: 1
    is_condition_post_install_script: false
    is_condition_update_and_upgrade: false
    is_condition_install_common_packages: false
    is_condition_ssh_port: false
    is_condition_ssh_login_with_key: false
    is_condition_post_completion_tasks_and_cleanup: false

  vars_files:
    - vault.yml

  pre_tasks:
    # `Pre gathering facts-Get and Set common variables`
    - name: ""
      import_tasks: pre_tasks/pre_gathering_facts-get_and_set_common_variables.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Private keys make read only`
    - name: ""
      import_tasks: pre_tasks/private_keys_readonly.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Virtualization and VT-d enabled` (will run only once, until forced)
    - name: ""
      import_tasks: pre_tasks/virtualization_vtd_enabled.yml
      when: not is_public_server_from_3rd_party

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

  tasks:
    # `Gathering facts manually`
    - name: Gather facts manually
      setup:

    # `Prerequisites`
    - name: ""
      import_tasks: tasks_conditions/prerequisites.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post install script` (will run only once, until forced)
    - name: ""
      import_tasks: tasks_conditions/post_install_script.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post install script`, Caller block"
      include_tasks: tasks/post_install_script.yml
      when: is_condition_post_install_script

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Update and upgrade` (will run only once, until 24 hours are passed or until forced)
    - name: ""
      import_tasks: tasks_conditions/update_and_upgrade.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Update and upgrade`, Caller block"
      include_tasks: tasks/update_and_upgrade.yml
      when: is_condition_update_and_upgrade

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Install common packages` (will run only once, until forced)
    - name: ""
      import_tasks: tasks_conditions/install_common_packages.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Install common packages`, Caller block"
      include_tasks: tasks/install_common_packages.yml
      when: is_condition_install_common_packages

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `SSH Port`
    - name: ""
      import_tasks: tasks_conditions/ssh_port.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `SSH Port`, Caller block"
      include_tasks: tasks/ssh_port.yml
      when: is_condition_ssh_port

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `SSH Login with Key` (will run only once, until `ssh_remote_public_key_path` is changed after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/ssh_login_with_key.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `SSH Login with Key`, Caller block"
      include_tasks: tasks/ssh_login_with_key.yml
      when: is_condition_ssh_login_with_key

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post Completion Tasks and Cleanup`
    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post Completion Tasks and Cleanup`, Caller block"
      include_tasks: tasks/post_completion_tasks_and_cleanup.yml
      when: is_condition_post_completion_tasks_and_cleanup
