############################################################################################################
#
#
#                                  PRE-TASK, MESSAGE, TASK_CONDITION & TASK
#
#     01. Virtualization and VT-d enabled (MESSAGE)
#
#
############################################################################################################
---
- name: Proxmox initial setup
  hosts: all
  gather_facts: no
  vars:
    pretask_taskandtaskcondition_message_sno: 1

  pre_tasks:
    # `Virtualization and VT-d enabled`
    - name: ""
      import_tasks: messages/virtualization_vtd_enabled.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

  tasks:
    - name: Gather facts manually
      setup:
