############################################################################################################
#
#
#                                  PRE_TASK, TASK_CONDITION & TASK
#
#     01. Pre gathering facts-Get and Set common variables (PRE_TASK)
#     02. Private keys make read only (PRE_TASK)
#     03. Virtualization and VT-d enabled (PRE_TASK)
#     04. Post gathering facts-Get and Set common variables (TASK only)
#     05. Prerequisites (TASK_CONDITION only)
#     06. Post install script
#     07. Update and upgrade
#     08. Install common packages
#     09. SSH Port
#     10. SSH Login with Key
#     11. Timezone
#     12. Update time from NTP
#     13. Hostname
#     14. WebGUI Port
#     15. Smartctl
#     16. VLAN aware
#     17. IOMMU
#     18. IOMMU modules
#     19. ISO Images
#     20. Email From
#     21. Email To
#     22. Postfix
#     23. ZFS Notifications
#     24. SSL Certificates
#     25. Fail2ban
#     26. Modify Add Network Adapters
#     27. Patch Network Dialogbox
#     28. Setting up LAN and Internet Bridge
#     29. Enable Tags view in Dashboard
#     30. Post Completion Tasks and Cleanup (TASK only)
#
#
############################################################################################################
---
- name: Proxmox initial setup
  hosts: all
  gather_facts: no
  vars:
    pretask_taskandtaskcondition_message_sno: 1
    is_condition_post_install_script: false
    is_condition_update_and_upgrade: false
    is_condition_install_common_packages: false
    is_condition_ssh_port: false
    is_condition_ssh_login_with_key: false
    is_condition_timezone: false
    is_condition_update_time_from_ntp: false
    is_condition_hostname: false
    is_condition_webgui_port: false
    is_condition_smartctl: false
    is_condition_vlan_aware: false
    is_condition_iommu: false
    is_condition_iommu_modules: false
    is_condition_iso_images: false
    is_condition_email_from: false
    is_condition_email_to: false
    is_condition_postfix: false
    is_condition_zfs_notifications: false
    is_condition_ssl_certificates: false
    is_condition_fail2ban: false
    is_condition_modify_add_network_adapters: false
    is_condition_patch_network_dialogbox: false
    is_condition_setting_up_lan_and_internet_bridge: false
    is_condition_enable_tags_view_in_dashboard: false
    is_condition_post_completion_tasks_and_cleanup: false

  vars_files:
    - vault.yml

  pre_tasks:
    # `Pre gathering facts-Get and Set common variables`
    - name: ""
      import_tasks: pre_tasks/pre_gathering_facts-get_and_set_common_variables.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Private keys make read only`
    - name: ""
      import_tasks: pre_tasks/private_keys_readonly.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Virtualization and VT-d enabled` (will run only once, until forced)
    - name: ""
      import_tasks: pre_tasks/virtualization_vtd_enabled.yml
      when: not is_public_server_from_3rd_party

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

  tasks:
    # `Gathering facts manually`
    - name: Gather facts manually
      setup:

    # `Post gathering facts-Get and Set common variables`
    - name: ""
      import_tasks: tasks/post_gathering_facts-get_and_set_common_variables.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Prerequisites`
    - name: ""
      import_tasks: tasks_conditions/prerequisites.yml

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post install script` (will run only once, until forced)
    - name: ""
      import_tasks: tasks_conditions/post_install_script.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post install script`, Caller block"
      include_tasks: tasks/post_install_script.yml
      when: is_condition_post_install_script

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Update and upgrade` (will run only once, until 24 hours are passed or until forced)
    - name: ""
      import_tasks: tasks_conditions/update_and_upgrade.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Update and upgrade`, Caller block"
      include_tasks: tasks/update_and_upgrade.yml
      when: is_condition_update_and_upgrade

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Install common packages` (will run only once, until forced)
    - name: ""
      import_tasks: tasks_conditions/install_common_packages.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Install common packages`, Caller block"
      include_tasks: tasks/install_common_packages.yml
      when: is_condition_install_common_packages

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `SSH Port`
    - name: ""
      import_tasks: tasks_conditions/ssh_port.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `SSH Port`, Caller block"
      include_tasks: tasks/ssh_port.yml
      when: is_condition_ssh_port

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `SSH Login with Key` (will run only once, until `ssh_remote_public_key_path` is changed after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/ssh_login_with_key.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `SSH Login with Key`, Caller block"
      include_tasks: tasks/ssh_login_with_key.yml
      when: is_condition_ssh_login_with_key

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Timezone`
    - name: ""
      import_tasks: tasks_conditions/timezone.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Timezone`, Caller block"
      include_tasks: tasks/timezone.yml
      when: is_condition_timezone

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Update time from NTP` (will run only once, until 24 hours are passed or until forced)
    - name: ""
      import_tasks: tasks_conditions/update_time_from_ntp.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Update time from NTP`, Caller block"
      include_tasks: tasks/update_time_from_ntp.yml
      when: is_condition_update_time_from_ntp

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Hostname`
    - name: ""
      import_tasks: tasks_conditions/hostname.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Hostname`, Caller block"
      include_tasks: tasks/hostname.yml
      when: is_condition_hostname

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `WebGUI Port`
    - name: ""
      import_tasks: tasks_conditions/webgui_port.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `WebGUI Port`, Caller block"
      include_tasks: tasks/webgui_port.yml
      when: is_condition_webgui_port

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Smartctl`
    - name: ""
      import_tasks: tasks_conditions/smartctl.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Smartctl`, Caller block"
      include_tasks: tasks/smartctl.yml
      when: is_condition_smartctl

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `VLAN aware`
    - name: ""
      import_tasks: tasks_conditions/vlan_aware.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `VLAN aware`, Caller block"
      include_tasks: tasks/vlan_aware.yml
      when: is_condition_vlan_aware

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `IOMMU`
    - name: ""
      import_tasks: tasks_conditions/iommu.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `IOMMU`, Caller block"
      include_tasks: tasks/iommu.yml
      when: is_condition_iommu

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `IOMMU modules`
    - name: ""
      import_tasks: tasks_conditions/iommu_modules.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `IOMMU modules`, Caller block"
      include_tasks: tasks/iommu_modules.yml
      when: is_condition_iommu_modules

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `ISO Images`
    - name: ""
      import_tasks: tasks_conditions/iso_images.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `ISO Images`, Caller block"
      include_tasks: tasks/iso_images.yml
      when: is_condition_iso_images

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Email From`
    - name: ""
      import_tasks: tasks_conditions/email_from.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Email From`, Caller block"
      include_tasks: tasks/email_from.yml
      when: is_condition_email_from

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Email To`
    - name: ""
      import_tasks: tasks_conditions/email_to.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Email To`, Caller block"
      include_tasks: tasks/email_to.yml
      when: is_condition_email_to

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Postfix` (will run only once, until files being changed is modified after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/postfix.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Postfix`, Caller block"
      include_tasks: tasks/postfix.yml
      when: is_condition_postfix

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `ZFS Notifications`
    - name: ""
      import_tasks: tasks_conditions/zfs_notifications.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `ZFS Notifications`, Caller block"
      include_tasks: tasks/zfs_notifications.yml
      when: is_condition_zfs_notifications

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `SSL Certificates`
    - name: ""
      import_tasks: tasks_conditions/ssl_certificates.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `SSL Certificates`, Caller block"
      include_tasks: tasks/ssl_certificates.yml
      when: is_condition_ssl_certificates

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Fail2ban` (will run only once, until files being changed is modified after running this or `fail2ban_filters_and_actions` content is changed or until forced)
    - name: ""
      import_tasks: tasks_conditions/fail2ban.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Fail2ban`, Caller block"
      include_tasks: tasks/fail2ban.yml
      when: is_condition_fail2ban

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Modify Add Network Adapters` (will run only once, until files being changed is modified after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/modify_add_network_adapters.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Modify Add Network Adapters`, Caller block"
      include_tasks: tasks/modify_add_network_adapters.yml
      when: is_condition_modify_add_network_adapters

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Patch Network Dialogbox` (will run only once, until files being changed is modified after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/patch_network_dialogbox.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Patch Network Dialogbox`, Caller block"
      include_tasks: tasks/patch_network_dialogbox.yml
      when: is_condition_patch_network_dialogbox

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Setting up LAN and Internet Bridge` (will run only once, until files being changed is modified after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/setting_up_lan_and_internet_bridge.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Setting up LAN and Internet Bridge`, Caller block"
      include_tasks: tasks/setting_up_lan_and_internet_bridge.yml
      when: is_condition_setting_up_lan_and_internet_bridge

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Enable Tags view in Dashboard` (will run only once, until files being changed is modified after running this or until forced)
    - name: ""
      import_tasks: tasks_conditions/enable_tags_view_in_dashboard.yml

    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Enable Tags view in Dashboard`, Caller block"
      include_tasks: tasks/enable_tags_view_in_dashboard.yml
      when: is_condition_enable_tags_view_in_dashboard

    - name: ""
      import_tasks: includes/pretask_taskandtaskcondition_message_sno_increment.yml

    # `Post Completion Tasks and Cleanup`
    - name: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task: `Post Completion Tasks and Cleanup`, Caller block"
      include_tasks: tasks/post_completion_tasks_and_cleanup.yml
      when: is_condition_post_completion_tasks_and_cleanup
