- name: "Declare all variables"
  set_fact:
    file_sno_type_prefix: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task:"
    section_name: "`Post Completion Tasks and Cleanup`"
  changed_when: false

- name: "{{ file_sno_type_prefix }} 001: {{ section_name }}, Update grub"
  command: update-grub
  when: is_condition_iommu or is_condition_iommu_modules

- name: "{{ file_sno_type_prefix }} 002: {{ section_name }}, Update initramfs"
  command: update-initramfs -u -k all
  when: is_condition_iommu or is_condition_iommu_modules

- name: "{{ file_sno_type_prefix }} 003: {{ section_name }}, Reboot the server"
  reboot:
    msg: "Reboot initiated by `Post Completion Tasks and Cleanup.yml`"
    reboot_timeout: 600
  when: is_condition_webgui_port or is_condition_iommu or is_condition_iommu_modules or is_condition_modify_add_network_adapters
