- name: "Declare all variables"
  set_fact:
    file_sno_type_prefix: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task:"
    section_name: "`VirtIO.iso`"
  changed_when: false

- name: "{{ file_sno_type_prefix }} 001: {{ section_name }}, Download `VirtIO.iso` file if it does not exist"
  get_url:
    url: "{{ virtio_iso_link.stdout }}"
    dest: /var/lib/vz/template/iso/{{ virtio_iso_parentdir.stdout }}.iso
