- name: "Declare all variables"
  set_fact:
    file_sno_type_prefix: "{{ '%02d' | format(pretask_taskandtaskcondition_message_sno | int) }}-Task:"
    section_name: "`ZFS Notifications`"
  changed_when: false

- name: "{{ file_sno_type_prefix }} 001: {{ section_name }}, Backup current `/etc/zfs/zed.d/zed.rc`"
  shell: mkdir -p /root/proxmox_automation_install/backups/etc/zfs/zed.d/ && cp /etc/zfs/zed.d/zed.rc /root/proxmox_automation_install/backups/etc/zfs/zed.d/zed.rc_$(date +%Y%m%d-%H%M%S)
  failed_when: false

- name: "{{ file_sno_type_prefix }} 002: {{ section_name }}, Replace commented or other declared `ZED_EMAIL_ADDR=` with valid value"
  lineinfile:
    path: "/etc/zfs/zed.d/zed.rc"
    regexp: '^\s*#?\s*ZED_EMAIL_ADDR\s*='
    line: 'ZED_EMAIL_ADDR="root"'
    state: present
    insertafter: EOF
